language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-alkaw' ]; then cd .. && eval "mv $currentfolder generator-alkaw" && cd generator-alkaw; fi

